name: Run Tests on PR and Commit

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types: 
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Run Tests  # This is the name of the status check reported on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
